"""add rule priority

Revision ID: d0a77d914a66
Revises: e9c0d6c9155f
Create Date: 2026-03-12 00:05:01.652570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a77d914a66'
down_revision: Union[str, Sequence[str], None] = 'e9c0d6c9155f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_rules', sa.Column('priority', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_rules', 'priority')
    # ### end Alembic commands ###
