"""add parent id for hierchical accounts

Revision ID: e9c0d6c9155f
Revises: 54b50a2f6f7d
Create Date: 2026-03-11 23:54:31.830079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c0d6c9155f'
down_revision: Union[str, Sequence[str], None] = '54b50a2f6f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'accounts', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'parent_id')
    # ### end Alembic commands ###
